// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: ingest.proto

package ingestpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RecordBatch carries a group of records. Each entry is a JSON-encoded
// model.Record; encoding records as JSON avoids duplicating the (open, nested,
// heterogeneous) log schema in protobuf and matches the on-disk segment format.
type RecordBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       [][]byte               `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordBatch) Reset() {
	*x = RecordBatch{}
	mi := &file_ingest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordBatch) ProtoMessage() {}

func (x *RecordBatch) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordBatch.ProtoReflect.Descriptor instead.
func (*RecordBatch) Descriptor() ([]byte, []int) {
	return file_ingest_proto_rawDescGZIP(), []int{0}
}

func (x *RecordBatch) GetRecords() [][]byte {
	if x != nil {
		return x.Records
	}
	return nil
}

// Ack reports the highest committed offset for each source seen so far.
type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Committed     []*SourceOffset        `protobuf:"bytes,1,rep,name=committed,proto3" json:"committed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_ingest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_ingest_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetCommitted() []*SourceOffset {
	if x != nil {
		return x.Committed
	}
	return nil
}

// SourceOffset is a per-source high-water mark. source_key is model.Source.Key().
type SourceOffset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceKey     string                 `protobuf:"bytes,1,opt,name=source_key,json=sourceKey,proto3" json:"source_key,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceOffset) Reset() {
	*x = SourceOffset{}
	mi := &file_ingest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceOffset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceOffset) ProtoMessage() {}

func (x *SourceOffset) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceOffset.ProtoReflect.Descriptor instead.
func (*SourceOffset) Descriptor() ([]byte, []int) {
	return file_ingest_proto_rawDescGZIP(), []int{2}
}

func (x *SourceOffset) GetSourceKey() string {
	if x != nil {
		return x.SourceKey
	}
	return ""
}

func (x *SourceOffset) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

var File_ingest_proto protoreflect.FileDescriptor

const file_ingest_proto_rawDesc = "" +
	"\n" +
	"\fingest.proto\x12\x13simplelog.ingest.v1\"'\n" +
	"\vRecordBatch\x12\x18\n" +
	"\arecords\x18\x01 \x03(\fR\arecords\"F\n" +
	"\x03Ack\x12?\n" +
	"\tcommitted\x18\x01 \x03(\v2!.simplelog.ingest.v1.SourceOffsetR\tcommitted\"E\n" +
	"\fSourceOffset\x12\x1d\n" +
	"\n" +
	"source_key\x18\x01 \x01(\tR\tsourceKey\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset2R\n" +
	"\x06Ingest\x12H\n" +
	"\x06Stream\x12 .simplelog.ingest.v1.RecordBatch\x1a\x18.simplelog.ingest.v1.Ack(\x010\x01B.Z,github.com/andyleap/simplelog/proto/ingestpbb\x06proto3"

var (
	file_ingest_proto_rawDescOnce sync.Once
	file_ingest_proto_rawDescData []byte
)

func file_ingest_proto_rawDescGZIP() []byte {
	file_ingest_proto_rawDescOnce.Do(func() {
		file_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ingest_proto_rawDesc), len(file_ingest_proto_rawDesc)))
	})
	return file_ingest_proto_rawDescData
}

var file_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ingest_proto_goTypes = []any{
	(*RecordBatch)(nil),  // 0: simplelog.ingest.v1.RecordBatch
	(*Ack)(nil),          // 1: simplelog.ingest.v1.Ack
	(*SourceOffset)(nil), // 2: simplelog.ingest.v1.SourceOffset
}
var file_ingest_proto_depIdxs = []int32{
	2, // 0: simplelog.ingest.v1.Ack.committed:type_name -> simplelog.ingest.v1.SourceOffset
	0, // 1: simplelog.ingest.v1.Ingest.Stream:input_type -> simplelog.ingest.v1.RecordBatch
	1, // 2: simplelog.ingest.v1.Ingest.Stream:output_type -> simplelog.ingest.v1.Ack
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ingest_proto_init() }
func file_ingest_proto_init() {
	if File_ingest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ingest_proto_rawDesc), len(file_ingest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ingest_proto_goTypes,
		DependencyIndexes: file_ingest_proto_depIdxs,
		MessageInfos:      file_ingest_proto_msgTypes,
	}.Build()
	File_ingest_proto = out.File
	file_ingest_proto_goTypes = nil
	file_ingest_proto_depIdxs = nil
}
