// Code generated by protoc-gen-go-drpc. DO NOT EDIT.
// protoc-gen-go-drpc version: v1.0.0
// source: ingest.proto

package ingestpb

import (
	context "context"
	errors "errors"
	protojson "google.golang.org/protobuf/encoding/protojson"
	proto "google.golang.org/protobuf/proto"
	drpc "storj.io/drpc"
	drpcerr "storj.io/drpc/drpcerr"
)

type drpcEncoding_File_ingest_proto struct{}

func (drpcEncoding_File_ingest_proto) Marshal(msg drpc.Message) ([]byte, error) {
	return proto.Marshal(msg.(proto.Message))
}

func (drpcEncoding_File_ingest_proto) MarshalAppend(buf []byte, msg drpc.Message) ([]byte, error) {
	return proto.MarshalOptions{}.MarshalAppend(buf, msg.(proto.Message))
}

func (drpcEncoding_File_ingest_proto) Unmarshal(buf []byte, msg drpc.Message) error {
	return proto.Unmarshal(buf, msg.(proto.Message))
}

func (drpcEncoding_File_ingest_proto) JSONMarshal(msg drpc.Message) ([]byte, error) {
	return protojson.Marshal(msg.(proto.Message))
}

func (drpcEncoding_File_ingest_proto) JSONUnmarshal(buf []byte, msg drpc.Message) error {
	return protojson.Unmarshal(buf, msg.(proto.Message))
}

type DRPCIngestClient interface {
	DRPCConn() drpc.Conn

	Stream(ctx context.Context) (DRPCIngest_StreamClient, error)
}

type drpcIngestClient struct {
	cc drpc.Conn
}

func NewDRPCIngestClient(cc drpc.Conn) DRPCIngestClient {
	return &drpcIngestClient{cc}
}

func (c *drpcIngestClient) DRPCConn() drpc.Conn { return c.cc }

func (c *drpcIngestClient) Stream(ctx context.Context) (DRPCIngest_StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, "/simplelog.ingest.v1.Ingest/Stream", drpcEncoding_File_ingest_proto{})
	if err != nil {
		return nil, err
	}
	x := &drpcIngest_StreamClient{stream}
	return x, nil
}

type DRPCIngest_StreamClient interface {
	drpc.Stream
	Send(*RecordBatch) error
	Recv() (*Ack, error)
}

type drpcIngest_StreamClient struct {
	drpc.Stream
}

func (x *drpcIngest_StreamClient) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcIngest_StreamClient) Send(m *RecordBatch) error {
	return x.MsgSend(m, drpcEncoding_File_ingest_proto{})
}

func (x *drpcIngest_StreamClient) Recv() (*Ack, error) {
	m := new(Ack)
	if err := x.MsgRecv(m, drpcEncoding_File_ingest_proto{}); err != nil {
		return nil, err
	}
	return m, nil
}

func (x *drpcIngest_StreamClient) RecvMsg(m *Ack) error {
	return x.MsgRecv(m, drpcEncoding_File_ingest_proto{})
}

type DRPCIngestServer interface {
	Stream(DRPCIngest_StreamStream) error
}

type DRPCIngestUnimplementedServer struct{}

func (s *DRPCIngestUnimplementedServer) Stream(DRPCIngest_StreamStream) error {
	return drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

type DRPCIngestDescription struct{}

func (DRPCIngestDescription) NumMethods() int { return 1 }

func (DRPCIngestDescription) Method(n int) (string, drpc.Encoding, drpc.Receiver, interface{}, bool) {
	switch n {
	case 0:
		return "/simplelog.ingest.v1.Ingest/Stream", drpcEncoding_File_ingest_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return nil, srv.(DRPCIngestServer).
					Stream(
						&drpcIngest_StreamStream{in1.(drpc.Stream)},
					)
			}, DRPCIngestServer.Stream, true
	default:
		return "", nil, nil, nil, false
	}
}

func DRPCRegisterIngest(mux drpc.Mux, impl DRPCIngestServer) error {
	return mux.Register(impl, DRPCIngestDescription{})
}

type DRPCIngest_StreamStream interface {
	drpc.Stream
	Send(*Ack) error
	Recv() (*RecordBatch, error)
}

type drpcIngest_StreamStream struct {
	drpc.Stream
}

func (x *drpcIngest_StreamStream) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcIngest_StreamStream) Send(m *Ack) error {
	return x.MsgSend(m, drpcEncoding_File_ingest_proto{})
}

func (x *drpcIngest_StreamStream) Recv() (*RecordBatch, error) {
	m := new(RecordBatch)
	if err := x.MsgRecv(m, drpcEncoding_File_ingest_proto{}); err != nil {
		return nil, err
	}
	return m, nil
}

func (x *drpcIngest_StreamStream) RecvMsg(m *RecordBatch) error {
	return x.MsgRecv(m, drpcEncoding_File_ingest_proto{})
}
